resources:
- deployment.yaml

images:
- name: compliance-operator
  newName: quay.io/rh-ee-thafeez/compliance-operator
  newTag: pr-1091
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
