resources:
  - ocp-virt-permissions.yaml
  - ocp-virt-rbac-binding.yaml
  - kubevirt-macspoof-nad.yaml
  - kubevirt-macspoof-sriov.yaml
  - kubevirt-nonroot-feature-gate-is-enabled.yaml
  - kubevirt-no-permitted-host-devices.yaml
  - kubevirt-persistent-reservation-disabled.yaml
  - tailored-profile.yaml
  - scan-setting-binding.yaml
